name: GCR Cleaner

on:
  workflow_dispatch:
    inputs:
      olderThanHours:
        description: Age limit [h]
        required: true
        default: '24'
jobs:
  clean_gcr:
    runs-on: ubuntu-latest
    name: Clean GCR
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
#      - name: Set up Cloud SDK
#        uses: google-github-actions/setup-gcloud@v0
#        with:
#          project_id: ory-test-338911
#          service_account_key: ${{ secrets.TEST_SA_ARTIFACTS }}
#          export_default_credentials: true
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.TEST_SA_ARTIFACTS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Clean
        shell: bash
#        env:
#          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.TODO }}"
        run: |
          set -e
          echo ${{ inputs.olderThanHours }}
          echo $GOOGLE_APPLICATION_CREDENTIALS
          gcloud version
          echo "-------"
          gcloud info
          echo "Finished"
          
