name: Release Step 1 - sync RC branch

on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      test1:
        type: choice
        description: Release type
        options:
          - 'Full release'
          - 'Only cherry picks'
        required: true
      test3:
        description: Commit ID's
        required: false
        default: ''

jobs:
  sync-release-candidate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_PA_TOKEN}}
      - name: Sync release-candidate branch
        shell: bash
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"  
          git branch
          git fetch origin rc
          #git reset --hard rc
          git checkout rc
          #git checkout rc
          git status
          git diff ..main | git apply -
          git add .
          git commit -m "Sync from master"
          git push
          export NEW_COMMIT_ID=$(git rev-parse HEAD)
          echo "::set-env name=NEW_COMMIT_ID::NEW_COMMIT_ID"
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "release-candidate synced :rocket: - https://github.com/adamwalach/github-actions-test/commit/${{env.NEW_COMMIT_ID}}"

#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v3
#        with:
#          branch: rc
#          base: main